CREATE TABLE CBOARD(
	BNUM INT PRIMARY KEY AUTO_INCREMENT,
	MID VARCHAR(20) NOT NULL,
	MNICKNAME VARCHAR(20) NOT NULL,
	BTITLE VARCHAR(50) NOT NULL,
	BCONTENT VARCHAR(500) NOT NULL,
	BCNT INT DEFAULT 0,
	BDATE VARCHAR(20) NOT NULL
);

SELECT * FROM USER_TABLES;

DROP TABLE CBOARD;
SELECT * FROM CBOARD;

SELECT * FROM (SELECT C.*, ROWNUM FROM (SELECT * FROM CAR ORDER BY ROWNUM ) C WHERE ROWNUM <= 2 ) WHERE ROWNUM >= 1;

SELECT * FROM CBOARD ORDERS LIMIT 0,3;

SHOW DATABASES;
SHOW KIMDB;
SELECT * FROM CBOARD;
INSERT INTO CBOARD values (8, "park1234", "왕짱맨", "1111", "AA", "1", "2022");
INSERT INTO CBOARD values (9, "park1234", "왕짱맨", "2222", "AA", "1", "2022");
INSERT INTO CBOARD values (10, "park1234", "왕짱맨", "3333", "AA", "1", "2022");
INSERT INTO CBOARD values (11, "park1234", "왕짱맨", "2222", "AA", "1", "2022");
INSERT INTO CBOARD values (12, "park1234", "왕짱맨", "33322", "AA", "1", "2022");

SELECT * FROM CBOARD WHERE MID = 'park1234';

update cboard set mid='park1234' where mid='(알수없음)';

show tables;